### ISSUE TITLE
Schedule for "The Well" -- Special Trolley Route

### ISSUE THREAD

**Issue by greenlinktransit** [hackgvl/trolley-tracker#103]
[November 2015 BSWA Grid (002) - CFG.xlsx](https://github.com/codeforgreenville/trolley-tracker/files/22879/November.2015.BSWA.Grid.002.-.CFG.xlsx)

**Comment by bikeoid** [comment]
Thanks - the Greenlink alert for this weekend at http://www.ridegreenlink.com/AlertCenter.aspx?AID=61 indicates that Saturday's game is at 7:00PM, but it's actually at 3:00PM.   I'll schedule Saturday's Well route for 3PM.

**Comment by greenlinktransit** [comment]
That's odd.  The hard-copy calendar I have says that the game is at 7PM, but online it says 3PM.  I'm assuming there was a misprint. 

Anyway, good catch! I'll update our service alert.

**Comment by bikeoid** [comment]
What if a Sunday event runs until 10:00PM?  Does the Trolley serve only the opening part, or is service extended until 1 hour after the show - 11:00PM, or is the Well not on the route at all that day?

**Comment by greenlinktransit** [comment]
It's my understanding that we do not extend our trolley hours to accommodate events. If an event ends or begins before our normal operating hours, then people will need to find a different way to get to or from the event. I'll double-check with Steve.

**Comment by greenlinktransit** [comment]
Talked to Steve and Mark -- we do not extend our trolley operating hours for hockey games or special events at the Well, but we will for Clemson Basketball games (we're contractually obligated to provide service for those games).

**Comment by greenlinktransit** [comment]
Here's the December schedule for "The Well."  Because the file is a PDF, I wasn't able to extract the events that we will not be servicing.  Please do not post any events on Monday - Wednesday and anything outside of our normal operating hours (except for the Clemson basketball games).

[December 2015 BSWA Grid.pdf](https://github.com/codeforgreenville/trolley-tracker/files/41562/December.2015.BSWA.Grid.pdf)

**Comment by bikeoid** [comment]
I noticed that Trolley #6 was functioning as a shuttle directly between University Square and The Well during the game last night.   So is this the way The Well will be handled from now on when both trolleys are running?

**Comment by greenlinktransit** [comment]
Steve said that the Trolley should never run directly between the Well & County Square.  He'll speak with the driver to see why they did that.  Thanks for letting me know.

**Comment by bikeoid** [comment]
What is the Trolley holiday schedule for operation - specifically on the days:

Christmas Eve
Christmas Day
New Years Eve 
New Years Day
?

**Comment by greenlinktransit** [comment]
Mike -- just confirmed that we aren't running the trolleys on any of those days.

**Comment by greenlinktransit** [comment]
Not sure how/if you guys want to post this, but the Greenville Drive schedule has been released, as has the College Baseball schedule at Fluor field.  Greenlink is contractually obligated to service Fluor Field anytime there's a game or special event held there.  

http://www.milb.com/schedule/index.jsp?sid=t428 
[2016 College Baseball Schedule.docx](https://github.com/codeforgreenville/trolley-tracker/files/81177/2016.College.Baseball.Schedule.docx)

**Comment by greenlinktransit** [comment]
[FEB 2016 BSWA SCHEDULE.pdf](https://github.com/codeforgreenville/trolley-tracker/files/99531/FEB.2016.BSWA.SCHEDULE.pdf)

Here's the February BSWA schedule...

**Comment by ajhodges** [comment]
Apparently the route is changing tonight for the Republican debates?

**Comment by greenlinktransit** [comment]
The trolley is detouring off of Main starting at McBee while the streets are closed

**Comment by greenlinktransit** [comment]
[2016 College Baseball Schedule.docx](https://github.com/codeforgreenville/trolley-tracker/files/134952/2016.College.Baseball.Schedule.docx)
The College baseball schedule is out.  We will be running the trolley 2 hours before start time and 1 hour after end time (with the games lasting 3 hours) regardless of whether the game falls on a regular service day.

**Comment by greenlinktransit** [comment]
The March BSWA schedule....
[March 2016 Grid.pdf](https://github.com/codeforgreenville/trolley-tracker/files/148231/March.2016.Grid.pdf)

**Comment by greenlinktransit** [comment]
[May 2016 BSWA Schedule.pdf](https://github.com/codeforgreenville/trolley-tracker/files/238582/May.2016.BSWA.Schedule.pdf)

**Comment by bikeoid** [comment]
Just checking - I thought that there was no more BSWA service?

Also, just today coincidentally, the flexible 'schedule override' feature is working.   I would like to plan to train someone at Greenlink on how to set the scedule now.   Pick a day next week (or later) and I'll see if I can work it in.

**Comment by greenlinktransit** [comment]
We will be servicing BSWA only for graduation events.  I think there are a couple in June, as well, so please expect to see that schedule when it is released.

Let me get back to you on the schedule training.  Not sure who that person (or persons) will be.

**Comment by greenlinktransit** [comment]
Wednesday, Thursday, and Friday afternoon look good on our end.

**Comment by bikeoid** [comment]
Wednesday afternoon, May 4 works for me.

Re: Graduations - are they served outside of normal trolley hours?
- Is this a direct shuttle between University Square and BWSA?    I notice that it also mentions a shuttle between RWOC and BWSA for the Clemson event.

**Comment by greenlinktransit** [comment]
How about 2PM on Wednesday, May 4th? I can reserve our conference room that has a computer/projector.  Nicole, our Marketing & Development guru will meet with you, as will at least one of our dispatchers.

Regarding graduations....our trolleys should never run directly from County Square to BSWA.  If you ever see this in your tracking report, please let me know and I'll notify our GM. Greenlink will service the graduation events at BSWA so long as they fall within our normal operating hours.  No idea what the WROC shuttle is.....it's not us.

**Comment by greenlinktransit** [comment]
@bikeoid correction....we're only servicing BSWA on May 5th (Greenville Tech Graduation) and May 7th (Clemson Graduation).  Please disregard all of the other events at BSWA

**Comment by bikeoid** [comment]
Re: Meeting on schedule training - 2PM on Wednesday May 4 works for me!

**Comment by greenlinktransit** [comment]
@bikeoid sound good.  See you then

**Comment by greenlinktransit** [comment]
@bikeoid A meeting was just scheduled at the same time as our trolley tracker training.  Nicole McAden, our Marketing & Dev Specialist, will be here for the training and I think you might have a dispatcher or two. Unfortunately, I can't make it.

Mike -- Ask for Nicole when you get here.  She'll take you back to the Conference Room where we'll have a computer and LCD screen ready if you need it.
