### ISSUE TITLE
Swamp Rabbits 

### ISSUE THREAD

**Issue by agautsc** [hackgvl/trolley-tracker#106]
I had a good coffee with the VP of Marketing for the :rabbit:  Swamp Rabbits :rabbit: . They are going to help promote the app in the stadium and over the loud speaker. They are also going to send us some specs for in stadium digital signage. If we can design the ads they will add them to the rotation. 

If there are folks who are interested in helping with some marketing type things please :raising_hand:

**Comment by jeremywight** [comment]
Awesome! Great work Adam!

**Comment by Linktheoriginal** [comment]
Awesome!
