### ISSUE TITLE
Transitime open source transit software

### ISSUE THREAD

**Issue by bikeoid** [hackgvl/trolley-tracker#107]
[ Great find by @greenlinktransit, starting new issue ]

This could have been used for our Trolley Tracker, but we'd have to trade off by adding complexity of working with GTFS for route and stop definition and give up some of our custom features.   ( I haven't found any open source GTFS editor that's reasonably useful - there are some commercial GTFS editors though)

That being said, this application would be very applicable to the rest of the city buses as a way to add vehicle tracking to assist Greenlink dispatch and riders.   It requires a full GTFS dataset for maximum usefulness, along with a beacon and data interface per vehicle.  I can't see that it has further AVL functions such as cash box interface and passenger counting by stop, etc, but those wouldn't be too difficult to add onto the base software package.

**Comment by bikeoid** [comment]
For quick reference:
 * Main web site http://www.transitime.org
 * Award http://devpost.com/software/transitime-open-source-real-time-transit-information
 * Code https://github.com/Transitime/core

**Comment by greenlinktransit** [comment]
For what it's worth, I have Greenlink's GTFS file for all of the normal fixed routes.  Hoping to build the Clemson routes in the near future.  Getting the Trolleys on GTFS is difficult because GTFS requires timed stops, which the Trolley does not have.
