### ISSUE TITLE
Huntsville AL Update

### ISSUE THREAD

**Issue by agautsc** [hackgvl/trolley-tracker#108]
Email from the lead of Code for Huntsville

"Hi Adams...

Just a quick note of gratitude and a quick update... no, we did not fall off the edge of the world. 

We are using the android tracker app. I put it on my phone and it worked right out of the box... Well done kudos!! We will probably create a branch here so we can change the default variables in the setting and a couple of other minor tweaks. If we run into any major issues we will coordinate with you. Adam H was right, it was all much easier than I was building it up in my mind. And all the Android dev work came right back to me once I got into the code.

As for the other parts, we are using a different stack... node.js (express.io) using sockets with the client so updates are very fast, and a mongolab instance for data repo. When we have that all down and a better web client we'll let you know so if you want to incorporate a sockets solution into your code you can. (https://github.com/codeforhuntsville/transitTracks - caution it is still rough around the edges).

Our schedule is ambitious, but that is because you did all of the hard work. We think we will have a public prototype running on a public facing website (we will not be doing client iOS or Android app at this time) in time for the Holiday Season in Downtown Huntsville which has a weekend entertainment trolley like Greensville. If that works out in the month of December we will roll out a system-wide application shortly after the new year. The app is running under development on http://transitTracks.herokuapp.com if the red trolley is far away from downtown that is because I'm still tracking my phone and not a trolley.

Anyway, this is getting way too long for a thank you note so I just say Thank you! Great work!"

**Comment by jeremywight** [comment]
Awesome! Do you know how they found it Adam?

**Comment by agautsc** [comment]
I was talking to them about ImagineThat.io

**Comment by jeremywight** [comment]
Nice

**Comment by agautsc** [comment]
Additional update:

From Larry:
We have had two successful weekends of trolley tracking so I think we are going to go with a live prototype starting this weekend...

I'm putting together the about page today and giving credits...

I'll list the Code for Greenville Brigade and would like to give special notice to Adam Hodges since the part of your code we are using is the tracker-agent.

Do you want me to list all of your team members? if so can you send me their names again. *Ed Note: Hodges asked to just list Code for Greenville and not to have any one person spotlighted.*

BTW we did go with an express.io and sockets solution on a node.js stack... using mongoDB for data.

Can see where we are today at http://transittracks.herokuapp.com sometime Friday morning I'll point out new domain HopAroundHuntsville.com at the Heroku server...
