### ISSUE TITLE
Feedback from David

### ISSUE THREAD

**Issue by agautsc** [hackgvl/trolley-tracker#126]
David is an iOS user

Hi TrolleyTracker,

I have some feedback to provide about my application using experience:

I would like to see the routes and stops displayed on the map during
off-schedule hours. It would make planning a visit around using the tolley
so much easier.

Cheers!

**Comment by ajhodges** [comment]
[I agree.](https://github.com/codeforgreenville/trolley-tracker-android-client/issues/22) Definitely would be an improvement on the schedule page. Thanks David!
