### ISSUE TITLE
Vehicle Locator Companies

### ISSUE THREAD

**Issue by greenlinktransit** [hackgvl/trolley-tracker#127]
[TRANSITiQ.pdf](https://github.com/codeforgreenville/trolley-tracker/files/96110/TRANSITiQ.pdf)

Guys, I was in Charlotte last week for a DOT seminar and I met someone who created a company called TRANSITiQ.  From my conversation with him it sounds like his product is almost identical to what you guys did for the trolleys (and he makes good money off of it).  His biggest client is the DC Circulator with a fleet of ~60 vehicles -- his smart phones are on each one.  Obviously, we at Greenlink are very grateful for what you guys have done with the Trolleys but if you ever want to consider bringing your product to market, you might want to look at how TRANSITiQ works. From my experience I can tell you that there is most definitely a market for transit vehicle tracking systems that 1) do not rely on the drivers, 2) are cost-effective, and 3) provide a user-interface for vehicle dispatchers.  

Anyway, just thought I'd share.

**Comment by jeremywight** [comment]
Thanks for thinking of us and gathering that intel!

On Tue, Jan 19, 2016 at 10:39 AM, greenlinktransit <notifications@github.com
