### ISSUE TITLE
Route Improvements

### ISSUE THREAD

**Issue by jeremywight** [hackgvl/trolley-tracker#128]
- Make sure that Routes on the iOS app reflect the active status flag (currently displaying inactive routes)
- When you select a Route from the schedule take them to a preview of the route with a header which displays the route name date and time selected; then draw the actual route on the map to give an example of what that route looks like

**Comment by greenlinktransit** [comment]
Guys, a local radio station would like to do an interview about the Trolley Tracker.  Are any of you available next Tuesday morning (2/2)? I can give them Greenlink's perspective but I think it would be interesting to have someone from Code for Greenville on there, as well.  Anyway, let me know when you have a chance. I think their studio is near Bob Jones University on Wade Hampton.

**Comment by ajhodges** [comment]
I nominate @agautsc, he has the prettiest voice.

**Comment by Linktheoriginal** [comment]
@dacohenii and I work down the street from there.  I nominate @agautsc or @jeremywight.

What radio station is covering it?

**Comment by greenlinktransit** [comment]
103.3 Earth FM

**Comment by agautsc** [comment]
@jeremywight are you able to do it? If not I can, but I've been interviewed a couple times for the trolley tracker and a different voice might be nice. 

PS: The Bitmoji plugin now shows up as an option in the GitHub comment. 

![bitmoji](https://da8lb468m8h1w.cloudfront.net/v2/cpanel/9047320-125161747_3-s4-v1.png?palette=1&width=246)

**Comment by jeremywight** [comment]
I could definitely jump in. Do we know what time?

**Comment by greenlinktransit** [comment]
Depends on our availability.  What does your schedule look like?

**Comment by jeremywight** [comment]
Best would be before 930am as I have my morning Standup at 10am, but if
need be I could move it @greenlinktransit

**Comment by greenlinktransit** [comment]
@jeremywight how does 8:30 AM on Tuesday sound? Shouldn't take more than 30 mins

**Comment by jeremywight** [comment]
https://github.com/codeforgreenville/trolley-tracker-ios-client/issues/17

**Comment by jeremywight** [comment]
Works for me @greenlinktransit

**Comment by greenlinktransit** [comment]
@jeremywight see you there

**Comment by greenlinktransit** [comment]
Jeremy - the address is 920 Wade Hampton
