### ISSUE TITLE
App download count

### ISSUE THREAD

**Issue by bikeoid** [hackgvl/trolley-tracker#129]
Are any numbers available for installed App count yet for both IOS and Android?

**Comment by agautsc** [comment]
330 total installs of Android. Last count, iOS was much higher. We're way over 1,000 for sure. @austin9350 has the exact number

![bitmoji](https://da8lb468m8h1w.cloudfront.net/v2/cpanel/8139922-125161747_3-s4-v1.png?palette=1&width=246)

**Comment by austin9350** [comment]
Current count is 741

**Comment by ajhodges** [comment]
:tada: 1k+ downloads in < 1mo is pretty impressive! Especially in the 'offseason'. Exciting stuff.
