### ISSUE TITLE
Next meeting/ideas for future CFG events

### ISSUE THREAD

**Issue by ajhodges** [hackgvl/trolley-tracker#132]
Hey guys, I'm thinking we should have another meeting in March or early April to kind of regroup, keep our momentum going in 2016, and prepare the tracker for summer traffic. So let's schedule that.

Also I was thinking about the future of CFG and brainstorming how to boost membership, increase engagement, come up with new ideas, etc. How about a hackathon? We could open up the trolley tracker to donations and explore the option of getting local businesses to purchase ad space in the 'stop detail' view of the app. Then use that money to fund a community-themed hackathon.

Just a thought.

**Comment by agautsc** [comment]
I made a Doodle: http://doodle.com/poll/dtp9bsp64h98etaq Let's agree on a date and meet

**Comment by jeremywight** [comment]
Agreed @ahodges I think last thing we left off on was updating the schedules to show on the map to notify users of what the schedules actually mean. Would love to see if we could get that knocked out in our time together. I think it would be very valuable to users.

**Comment by allella** [comment]
If the group is going to reconsider a "regular" day of the month, then please feast our eyes on this
https://data.openupstate.org/greenville-meetup-scheduling

**Comment by jeremywight** [comment]
Nice!

**Comment by allella** [comment]
A possible agenda item, the codeforgreenville.org domain is pending transfer. Wryen authorized it over the weekend. It's in OpenWork's NameCheap account until such time as we find a better home.

**Comment by bikeoid** [comment]
I looked at the IOS app schedule listing - multiple association resulting in all routes crossed with all schedules being included.   Since I don't have a Swift development environment, I tried to compile it in my head but ran out of stack space.    But I could probably model it in C# and come up with a pull request which would have a reasonable chance to work.

**Comment by agautsc** [comment]
Tuesday 3/8 is undefeated. @jeremywight  can you setup the Meetup? @allella Can you reserve the conference room. Also in mistake that's gotten everyone at least once https://data.openupstate.org/organization/code-for-greenville Jeremy's last name is Wight and not W'R'ight

**Comment by agautsc** [comment]
I will also mention that the newest project being worked on is a website that connects potential food and beer sponsors without meetups happening. @rhynodesigns is leading this charge. We might be able to discuss this some at the meeting as well. https://codeforgvl.imaginethat.io/bpa

**Comment by allella** [comment]
Conf 1 reserved 5:30-8

I think it go it wright this time -> https://data.openupstate.org/organization/code-for-greenville

**Comment by jeremywight** [comment]
hehehe. Thanks @agautsc... Booked!
http://www.meetup.com/Upstate-Code-for-America/events/229288625/

**Comment by ajhodges** [comment]
To summarize some of the last minute flurry of events and tack on some personal opinions of my own:

Next meeting is April 19th. AKA National Bring A Friend To CFG Night.

Ideas for growing CFG:
- Update the CFG website with "marketing" pages for our projects
- Approach someone who doesn't "fit in" with our current member demographic (think someone who would be a 3rd degree connection to most people on linked in) so we can better expand our reach via word-of-mouth
- Fliers promoting CFG to put up in break rooms for those of us with offices
- Look in to 'booth with a cause' at the saturday farmers market or other types of outreach
- Approach local schools for students looking to bolster resumes (psst, @agautsc, this is how we met)
- Roll with Beer & Pizza! Sounds like a great and interesting project with a practical application in our local tech community.
- Promote CFG using our Trolley Tracker app. Maybe an 'about us' page inside the application with a 'Get Involved!' link. Also we should ask for our website to be included on Trolley Tracker marketing signage

That's probably not everything, I just wanted to do a data dump before I forget everything in about an hour and a half.

**Comment by allella** [comment]
Thanks Hodgefest.

I may have an opportunity to "showcase applications and technology used in their field, by engaging the students in an interactive/hands-on presentation" at an event for high school students at an ECPI event on April 6th.

Mobility and consistency was an issue with past experience with a high schooler (Killian), but maybe we'll get lucky.

I'd say NEXT High school, but I think they are all freshman or sophomores, so mobility would seem like an issue, but certainly a group to talk with some time soon to get in front of their cast.

**Comment by allella** [comment]
TEDx table sponsorship is something like $1000-$2500 for for-profit. Might be able to get a free table if it's just for Code For Greenville but may be a fair amount of effort to create a compelling table and man it for such an all-day event.  Just an idea.  I suppose we use https://codeforgvl.imaginethat.io/codeforgvl or another stream for marketing ideas if we want to throw things out there and get feedback on ideas.
