### ISSUE TITLE
Trolley Tracker App Metrics Update

### ISSUE THREAD

**Issue by invisionjeremy** [hackgvl/trolley-tracker#139]
I'd like to have updated metrics on downloads/usage for iOS and Android. 
@austin9350 can you gather the metrics on App Store and @ajhodges can you gather on Play Store for tomorrows meeting?

**Comment by ajhodges** [comment]
![image](https://cloud.githubusercontent.com/assets/856738/14615916/07343aae-0576-11e6-8afa-e23a9013555f.png)

**Comment by invisionjeremy** [comment]
Boom! Awesome! Thanks Adam!

On Mon, Apr 18, 2016 at 2:58 PM, Adam Hodges <notifications@github.com>
wrote:

> [image: image]
> <https://cloud.githubusercontent.com/assets/856738/14615916/07343aae-0576-11e6-8afa-e23a9013555f.png>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforgreenville/trolley-tracker/issues/139#issuecomment-211529079>
>



-- 
__

Follow us on Twitter @InVisionApp <http://www.twitter.com/invisionapp>

Jeremy Wight
Engineering Manager at InVision <http://www.invisionapp.com/>

InVision - A Design Prototyping, Collaboration & Workflow Platform.
<https://www.youtube.com/watch?v=ClIbn_IF31U>

jeremy@invisionapp.com

**Comment by austin9350** [comment]
Around 1,300 downloads so far. I can show more information tomorrow evening.

**Comment by invisionjeremy** [comment]
Awesome! Thanks Austin!

On Mon, Apr 18, 2016 at 3:16 PM, Austin <notifications@github.com> wrote:

> Around 1,300 downloads so far. I can show more information tomorrow
> evening.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforgreenville/trolley-tracker/issues/139#issuecomment-211536957>
>



-- 
__

Follow us on Twitter @InVisionApp <http://www.twitter.com/invisionapp>

Jeremy Wight
Engineering Manager at InVision <http://www.invisionapp.com/>

InVision - A Design Prototyping, Collaboration & Workflow Platform.
<https://www.youtube.com/watch?v=ClIbn_IF31U>

jeremy@invisionapp.com
