### ISSUE TITLE
Trolley expansion 

### ISSUE THREAD

**Issue by agautsc** [hackgvl/trolley-tracker#142]
http://www.greenvilleonline.com/story/news/local/greenville/downtown/2016/05/09/downtown-trolley-expansion-could-include-augusta-road-west-greenville/84137896/

**Comment by ajhodges** [comment]
I can't find any other thread on our GitHub discussing the new trolley routes, so I'll just put this here.

Got an e-mail from my neighborhood mailing list pimping out the trolley tracker, good work spreading the word at those meetings! Also looks like I may be living walking distance to a trolley stop again :)

![image](https://cloud.githubusercontent.com/assets/856738/23706296/9561b324-03db-11e7-8d99-8f299887b91a.png)

**Comment by jeremywight** [comment]
Thanks Adam!
