### ISSUE TITLE
Hotel Partnerships

### ISSUE THREAD

**Issue by agautsc** [hackgvl/trolley-tracker#145]

**Comment by rhynodesigns** [comment]
copied from here:
https://github.com/codeforgreenville/trolley-tracker/issues/143#issuecomment-219917602

I went and spoke with Brandon at the Hyatt and they will not have any sort of stand or anything visible. I asked if he had heard of the trolley tracker app, he said no. He said most people think they provide transportation, but they hand out physical trolley maps, but are currently out of them.

I'm not sure we want to get into the 'making/distributing flyers' business. I think getting the workers there to suggest the trolley tracker would be simply a matter of request/training. Show them the app, and ask them to share with fellow workers.

I don't know what a conversation with someone higher up would be like, suggesting they hang a tv with the trolley tracking app on it...with restaurants and points of interest...
