### ISSUE TITLE
Hack Night Meeting

### ISSUE THREAD

**Issue by agautsc** [hackgvl/trolley-tracker#146]
@jeremywight We decided to meet next week for a hack night.

The meeting is going to be focused on 
1. Updating the API to allow for wait time estimates
2. Updating the API to add additional attractions like hotels and bars to the map
3. Hacking on Beer & Pizza codeforgvl.imaginethat.io/bpa 

Can you send it out the Meetup invite for this?

Thanks,
-Adam

**Comment by jeremywight** [comment]
Replied to the other thread before I saw this. Will do, both meetup and OW
Calendar. Wish I could join you guys. Looks like you had a very productive
night last night!!!
