### ISSUE TITLE
'With well' routes being scheduled but not followed

### ISSUE THREAD

**Issue by ajhodges** [hackgvl/trolley-tracker#153]
I've noticed over the last few weeks that the trolley routes have frequently been the 'the well' variant, but the trolleys aren't actually going over there, they're just going straight down main. Who can we let know about this? I think we've imported the schedule for the arena into our back-end under the assumption that the trolley will be going over there for every event. Are we sure this is the case? Or do we have rouge drivers?

It could be that I was checking the tracker when the event was over/before it had begun/etc... but if it's confusing enough to confuse me, it's confusing enough to confuse our users :)

**Comment by bikeoid** [comment]
I pulled the routes for Saturday and found that they did go over to the well at times, but I didn't break those out to see when that was.    They must be following the event schedules more closely than what is on the schedule.

Officially, the trolley cannot make a direct path from the parking lot to The Well, and I see that the drivers are now doing that by running the entire route when they go to the Well.

Officially, the trolley is supposed to skip 'The Towers' stop when it goes to The Well, but they all seem to circle back around and pick it up.
