### ISSUE TITLE
New trolleys and routes

### ISSUE THREAD

**Issue by bikeoid** [hackgvl/trolley-tracker#154]
Some stuff from the slack group:

New trolley routes status:   New trolley delivery dates not yet firm, but likely in June.  Before the new stops can be activated on any of the new routes, handicap-accessible concrete landing pads must be built.   Public works is starting to work on them, but may not finish all pads by the time the trolleys arrive.

note from pamela
[12:00 PM] 
The founder of Open Savannah was on my call with Code for America and he was very impressed with our Trolley Tracker app! :boom:
https://twitter.com/fancybike/status/859847729924767746

Also somewhat related - the Greenlink buses will again be outfitted with equipment for passenger boarding analysis and location tracking.   When the riders learn that there will be a new Greenlink app to show bus arrival, they brighten up and say "Just like the Trolley Tracker? Cool!"

New routes have been finalized and are now in the trolley tracker DB.  The names are "Top of Main", "Heart of Main", "Arts West" and "Augusta".   No stops have been created yet.

IT has the new phones on order for the new trolleys.

  The apps won't allow the route shape preview until they are on  a schedule, but feel free to edit the schedule on the dev server at http://yeahthattrolley.azurewebsites.net/.   As a test, preview what your app will do when fed 4 live routes.

**Comment by mblizzard-gvl** [comment]
We have one of the new phones in but are having issues with rooting 7.1. We should have this straight shortly. Has the app been tested on 7 yet?



Mike Blizzard
Technical Services Manager | IT Department
City of Greenville
864-467-5707



-------- Original message --------

**Comment by mblizzard-gvl** [comment]
All,

We have the new phones ready to begin testing.  We will need to install the beacon app to complete the setup.  We were thinking it may be useful to run the new phones in the existing trolleys in parallel with the existing phones for a couple of weeks to make sure everything looks good.   If it works as expected, Trolley 1 should have the same beacon data as Trolley 3 and Trolley 2 should have the same beacon data as Trolley 4.    First, does this sound sound like a good approach to testing?  Second, where do we get the beacon app and needed info for this?

Thanks

Mike Blizzard
City IT.

**Comment by ajhodges** [comment]
Hi Mike,

Sorry for the lack of response on my part. Here is the beacon app: https://play.google.com/store/apps/details?id=com.codeforgvl.trolleytracker

It's restricted by play store user (it's not public). We created a google account for the tracker, and I can share those credentials with you. You will need to use that account to sign in on the devices and make sure that automatic updates are enabled so we can push updates if needed (although the last update we needed was 1.5 years ago).

I still have not tested the app with 7.0+... I don't think there will be an issue, but I can definitely help debug if you run into issues. I really like the idea of doing a test run, and I'm wondering if @bikeoid has an easy way to 'disable' trolleys from showing up on the map for testing purposes? Otherwise, we do have a separate API/DB for testing purposes that we can use (easily configurable via a settings page in the beacon app) and then switch it over when we want to go live with the new devices.

I will send you an e-mail with the credentials and my contact info

Thanks,
Adam

**Comment by bikeoid** [comment]
I believe the parallel test is a good idea.   It wouldn't hurt to just go ahead and use the live database.   Even though there would be 2 trolleys running in the same location, the only possible user issue might be the trolley icon changing color on one update VS the next.    The rider trolley tracker app won't show any of the trolley information unless there is a route active.   It is best to use the diagnostic interface at http://api.yeahthattrolley.com/DBVisualizer?ActiveFilter=1  to see the new beacons.    Going directly to the live server will also be the easiest way to work with my monitoring tool.   We can confirm that both beacons turn on and off as the trolleys are started and stopped.

The only thing we'll need to do to accept the new beacons is to define the trolley numbers in the database at http://api.yeahthattrolley.com/Trolleys ; I can enter them this evening, or Nicole McAden can assist with this if you need them earlier.

**Comment by bikeoid** [comment]
The new trolley numbers will be 1701 and 1702 - those numbers will be on the outside of the trolley.

The new beacons may be configured to point to these numbers and perform any testing at any time.   The back end is now configured to accept those numbers.

If the numbers or terminology changes, it will be easy to update.

**Comment by ajhodges** [comment]
I just realized that we'll have to add some work items for the front-end UIs to handle more than two trolleys. I know that the Android currently only has two icons (purple/green) so we'll have to add some new colors. Do we know how many trolleys will be in operation simultaneously? I've gotta double check the code and make sure I'm not limiting things to two trolleys anywhere else.

I suppose a dynamic solution is probably the way to go... I went that route for the routes/stop markers. But (as we've discussed before) it's useful for all the front-end apps to have matching colors so someone can say "I'm on the purple trolley" to a friend and them be able to catch it. So either have consistent coloring based on Trolley ID on the front-end, or make the marker color a back-end property.

Just rambling - don't know if this is even the best place to spitball those ideas. @austin9350 @dacohenii any input?

**Comment by bikeoid** [comment]
Re: consistent trolley colors - as a hack, we could append a color spec #RRGGBB to the end of the trolley name, since it is not directly displayed to the riders (from what I remember).   Otherwise a field could be added.

**Comment by Linktheoriginal** [comment]
If we can add a hex color field that would be easiest I think.

**Comment by bikeoid** [comment]
I've added the field IconColorRGB to the dev server at http://yeahthattrolley.azurewebsites.net/ .   It should be published to the real server some time next week.     So anyone feel free to set better colors in the trolley settings on the dev server - I have no idea whether dark / light colors work best in the 3 apps, and if some colors should be avoided.   It may be an iterative process to finalize the colors.    We can just copy those colors to the production server.

In the meantime, I have modified the simulation to hand out 4 running trolley locations.   The main one updates every 2 seconds, and after 20 seconds the other 3 string along in a haphazard manner.  This can be viewed at http://yeahthattrolley.azurewebsites.net/DBVisualizer?ActiveFilter=1

Perhaps we should add a color field to the route definition as well?

**Comment by bikeoid** [comment]
Re: Route colors - A particular trolley may or may not run the same route during a schedule period.  As drivers come and go, and take breaks, trolleys may get switched up.   So riders could wrongly associate trolley colors with route colors if they happen to match.

**Comment by bikeoid** [comment]
The Trolley colors field change is now published to the production server.

**Comment by austin9350** [comment]
I've uploaded a new TestFlight build that adds support for the colors field, should be available sometime today.

**Comment by jeremywight** [comment]
Thanks all!

**Comment by bikeoid** [comment]
It works here !

**Comment by bikeoid** [comment]
What is the status of running with 4 routes and 4 trolleys?  Greenlink is getting close to switching to the new routes, and I wanted to be sure that the apps wouldn't crash (even if coloring is not optimal yet).   Riders will probably be OK to start with as long as they can see routes, stops, and trolley locations.

From last month's meeting, I believe the web app is ready.   What about IOS and Android?

**Comment by ajhodges** [comment]
Android will not crash with more than two trolleys, but the marker colors will alternate between Green and Purple until the dynamic color update is pushed, next week at the earliest.

**Comment by austin9350** [comment]
I can go ahead and submit the last TestFlight build for public release, I haven't seen any major issues with it and it seems to handle the additional trolleys/routes satisfactorily.

**Comment by mblizzard-gvl** [comment]
We have the phones ready but never ran them parallel with Trolley 1&2. Do we need to run them parallel or just wait and mount them in the new trollies?

Mike Blizzard
Technical Services Manager | IT Department
City of Greenville, SC
www.greenvillesc.gov<http://www.greenvillesc.gov>

On Jul 17, 2017, at 8:34 PM, Austin <notifications@github.com<mailto:notifications@github.com>> wrote:


I can go ahead and submit the last TestFlight build for public release, I haven't seen any major issues with it and it seems to handle the additional trolleys/routes satisfactorily.

-

**Comment by bikeoid** [comment]
I don't think they need to be run in parallel.   As long as there is confidence that they will turn off and on with the ignition switch, they can be directly mounted in the new trolleys.

**Comment by bikeoid** [comment]
How long will the IOS public release take to get through the Apple Store review?

**Comment by jeremywight** [comment]
Typically 1-2 days, but up to 4

**Comment by austin9350** [comment]
Just released the update at the work night, should be live in the store now.

**Comment by bikeoid** [comment]
We now have a start date for the new trolleys and new routes, unless something else comes up.  Thursday, August 3 at 6pm

**Comment by ajhodges** [comment]
I was just chatting with some people on Nextdoor about the app, someone noticed that the only stops for the 'Augusta' route are downtown. Are there going to be regular stops in neighborhoods for that route? Not sure who should get that question...

**Comment by bikeoid** [comment]
The Augusta route direction accidentally got flipped by my tool, so there were no stops on the right side of the route.    I corrected that and let there be stops!  They show up now in my Android app.

I see that the IOS app doesn't refresh the schedules unless the app is restarted - I'll generate an issue.

**Comment by bikeoid** [comment]
Some pictures of the new trolley: 


![1702](https://farm5.staticflickr.com/4344/35546439673_93a28e6fd4_b.jpg)
![1702](https://farm5.staticflickr.com/4353/36186099382_25750ba39c_b.jpg)
![1702](https://farm5.staticflickr.com/4422/35546439963_db867f27b0_b.jpg)

**Comment by bikeoid** [comment]
Just a note: the simulator will not be running for a week (routes only, no trolleys)

**Comment by bikeoid** [comment]
There were only 3 trolleys running tonight (Thursday), and only 2 beacons were operating.   This is likely because of all the equipment modifications being installed on trolleys this week:

1.   A.D.A. compliant voice annunciator for automated voice stop announcements.
2.  An on-board information text light bar (approximately 4" X 3 feet).
3. Passenger counting device on doorway.
 4.  Tablet in a permanent mount facing driver.   Driver will log in with their identity and pair the current trolley to a route.   We might be able to pull this information from their new system after it is operational to keep our trolley and route colors matched.

  From the words of one of the Greenlink guys, it's a real rats nest of wiring from all the new equipment, and that's likely why the beacons are disconnected at times.
