### ISSUE TITLE
Add designated stops only warning message to all apps 

### ISSUE THREAD

**Issue by bikeoid** [hackgvl/trolley-tracker#156]
Greenlink has received many complaints from passengers who want to be let off of the trolley, or board the trolley, between stops.
This is unsafe and is against their policy.   

Would it be possible to add some disclaimer or notification to the trolley tracker client apps that says something along the lines of:

“To ensure safety, passengers are restricted to board and exit the trolley at designated trolley stops.”

This would need to be added to the 3 apps: web, IOS and Android.   Also some logic to determine when to show it to avoid being bothersome.   No more than once/day?  Once / week?  A checkbox to say "never show this again"?   One time only per user?  A toast that shows only a few seconds while loading?

**Comment by stampthecoder** [comment]
Hmm... I think a disclaimer during loading would be less complex and not rely on scheduling logic for each app which would have to be something else to maintain over time. This seems like a rule that needs to be expressed.

**Comment by jeremywight** [comment]
Agreed, maybe in the settings or under the "?" bubble rather than obtusely
in the users view?

**Comment by austin9350** [comment]
New build is processing through TestFlight which includes the disclaimer message. Currently it shows for 10 seconds on each app launch, and can also by dismissed manually by tapping on it. The timing can be easily adjusted if needed.

Other changes in this build are as follows:

- Schedules refresh on the quarter hour (similarly to the way routes do)
- Updated Stop pins on the map (these are smaller now, to reduce visual clutter)
- Trolley annotations always appear in front of stop annotations (unless a stop annotation has been selected, then the selected annotation is the frontmost)

Known issues in this build:
- "Locate Me" button does not work

**Comment by jeremywight** [comment]
Great stuff Austin!

**Comment by bikeoid** [comment]
The smaller stop pins are great to make it easier to see things now with all the routes.

I didn't see the disclaimer message if I had checked the app with no routes running, but it did show properly when I restarted the app.   I think that's probably OK.

The routes didn't show at first when I opened the app until I switched to the schedule page and back.
