### ISSUE TITLE
Users would like to have a way to clearly know which trolley is running on which route

### ISSUE THREAD

**Issue by jeremywight** [hackgvl/trolley-tracker#159]
I've received several user submitted feedback emails about confusion of which trolley is running which route now that we have the new routes added.

A user would like an easy way to differentiate routes, trolleys and direction of travel, and understand which trolley is running which route. 

Perhaps in the UI we could make the labelingof the routes and trolley more clear somehow? Possibly numbering the trolley and route? 

I received about 4 comments about this so it seems that there is some user confusion here that we should attempt to resolve @bikeoid @austin9350 @ajhodges

**Comment by bikeoid** [comment]
Route path direction arrows could help also.

**Comment by austin9350** [comment]
If we are able to know what route a particular Trolley is running, one thing I had thought we could do client side is if a user taps on a Trolley (or Stop), we could hide (or at least dim) all the other Trolleys and Routes/Stops.

**Comment by jeremywight** [comment]
That's a great idea Austin. Also I noticed I using the iOS app this weekend
that it starts at a fixed zoom which is pretty wide. It might be better to
auto zoom in focused closer to your location.

**Comment by jeremywight** [comment]
From a user:

Consistent color coding of the routes (the Map page and the Schedule pages)
would help enormously, as would showing the moving  trolley progress on the
Schedule page instead of (or in addition to) the Map page. So, to see it
from a user's protective: he or she could be looking for a red route, or a
blue route or a yellow route. Consistent color coding would really clarify
the routes for the user.

**Comment by austin9350** [comment]
@jeremywight Right now I have it set to zoom the map to the downtown area rather than the user's location when the app launches. My thinking was that if the user wasn't close enough to downtown to see any Trolleys or Routes, there wouldn't be much to look at when the app launched. 
Maybe I could start with the fixed downtown location, and then when the app gets the user's location, if that location is near downtown, zoom closer in to them. What do you think?

**Comment by austin9350** [comment]
@bikeoid you mentioned something about electronic route annunciator headboards, do we know how they are planning to control those?

**Comment by bikeoid** [comment]
@austin9350 Good point about the electronic route annunciator headboards - if we could connect to them, that would be a great way to know which route a trolley is running.   I'll try to get more information on this.

Also, FYI - currently they are planning to put the AVL (Automatic Vehicle Location) on Greenlink buses starting testing near the end of the year.   It was also mentioned that they might put these systems on the trolleys as a parallel / redundant system (which could also collect passenger counts, etc).  That plan could change however.

**Comment by jeremywight** [comment]
@austin9350 Yeah I think that is a great plan if it's not to hard to implement. Our use case was we were downtown, but we had to re-center on ourselves and zoom in to figure out where we were in relation to the trolley. I think startup, centered on downtown, if your location is within that map area, once the app has your location, zoom in to your location with maybe an area of like 1mi radius. 

So, this full downtown size should zoom to about this second size if my pin were at Broad and Main.

![Startup Default](https://user-images.githubusercontent.com/8245600/29392889-a0ddc9e6-82ce-11e7-9d28-5352dabd8dfd.PNG)

![Zoomed in on my location EX: Broad and Main](https://user-images.githubusercontent.com/8245600/29392896-b0aa39a4-82ce-11e7-8a80-24b7e49710e5.PNG)

**Comment by austin9350** [comment]
@jeremywight @bikeoid  I've been playing around with the color-coding some and I think I have it working, at least an initial implementation. 

Basically each Trolley is assigned a score for how likely it is to be assigned to a particular route based on how many stops of that route it's been seen at compared to how many total stops that route has. 

The algorithm probably needs to some refinement to handle a Trolley switching routes, maybe using last-seen dates as a tie-breaker if it's been seen at all stops of more than one route. But until/unless we're able to implement something where the driver can explicitly set a route I think this has promise.

![img_2804](https://user-images.githubusercontent.com/2276307/29491454-a5d752b0-852a-11e7-8041-95dc279543dd.PNG)

**Comment by bikeoid** [comment]
I think that should work pretty well, especially for now when the trolley  <> route match won't change very often.  It could probably be made sticky between scheduled days.

It seems like this might make sense to do on server side since it requires looking over a span of time?    If so, would that be just adding a color to the trolley definition (except that since it could change so easily, we might have to expand the running trolleys message to put colors there).

**Comment by jeremywight** [comment]
Great thinking Austin! Excited to see how this pans out. Would definitely
be good to spend some time testing before going to live to GA if that's the
method we implement.

**Comment by austin9350** [comment]
I agree it makes sense to implement this logic server-side.

I'm thinking it might involve two things added to the Route responses. 
- A color field (similar to the one current on Trolleys)
- An array of IDs of Trolleys running that route

The combination of those two things would allow for several client-side features we've been discussing.
1. The color-matching of Trolleys-Routes-Stops
2. Highlighting a Trolley and it's Route in response to a user selecting annotations on the map
3. Updating the Route detail view (shown when the user taps on a Route in the Schedule view) to include Trolley's assigned to that Route

In my head I think those two fields would work best, but I haven't worked it out in code so it's entirely possible I'm overlooking something. What do you all think?

I should be able to make if out for at least a little while this Tuesday so hopefully we can chat about it more there.

**Comment by bikeoid** [comment]
@austin9350 , the route colors are being served on the dev server - I'm not sure if I matched the official Greenlink colors correctly - could you check this?

**Comment by bikeoid** [comment]
@austin9350  , also - if you have the login to the dev server, feel free to adjust the route colors

**Comment by austin9350** [comment]
@bikeoid  @jeremywight  Just uploaded a new TestFlight build (23), this one has the route colors hard-coded based on the route names. Also, I realized why the Greenlink map has all the stops the same color. When the routes overlap they share stops so if we show a particular route color it could be confusing to the user (i.e., "is this not a legit stop for this other route?"
Based on that, I made the stops all a dark gray. 
I'll probably go ahead and submit this version and if everything checks out during testing I can release it for this weekend. 

Next up I'll look at pulling the Route colors from the Route response from the Dev server, and see about adding route arrows.

**Comment by bikeoid** [comment]
The latest TestFlight looks good here, where they're running 2 trolleys on the ball game route.   I've submitted the dev version which has route colors for production, but it hasn't published and I haven't heard any update on a possible publication date.

**Comment by jeremywight** [comment]
Quick pass looks good.

**Comment by bikeoid** [comment]
An update: the production server is now running 1.3.9, the version which include colors on routes.

**Comment by jeremywight** [comment]
Thanks Mike!

**Comment by austin9350** [comment]
The update I submitted has been approved by Apple and is ready to release. I’ve been checking it tonight with more routes active and it seems to be working fine. If you all agree I can go ahead and release it.

**Comment by bikeoid** [comment]
I've been keeping an eye on it also - much nicer and so much easier to figure out what's going on without needing to zoom too far.

**Comment by jeremywight** [comment]
Let's do it Austin.
.. Release the kraken!

**Comment by austin9350** [comment]
Kraken has been released! Should be emerging shortly.
