### ISSUE TITLE
Spark Electron: Cellular dev kit with a simple data plan

### ISSUE THREAD

**Issue by agautsc** [hackgvl/trolley-tracker#18]
I don't think any part of this makes exact sense for what we're doing, but I'll still drop it here.

https://www.kickstarter.com/projects/sparkdevices/spark-electron-cellular-dev-kit-with-a-simple-data?ref=home_popular

**Comment by thedanfields** [comment]
That's pretty awesome.  I'll see if I can figure out if it, or an
additional shield, can provide gps coords.

**Comment by jeremywight** [comment]
Awesome! Dan did you see that I have a SIM running on T-Mobile that is active and ready? The Android phone that I thought was going to work isn't charging via the cable anymore so I don't think it will work, but I've got an active SIM that will work if anyone has a device.
