### ISSUE TITLE
Friday Lunch Route 

### ISSUE THREAD

**Issue by agautsc** [hackgvl/trolley-tracker#21]
Kathy from Greenlink answered in the comments https://codeforgvl.imaginethat.io/trolleytracker/i/4820

**Comment by Linktheoriginal** [comment]
Going to add this to the web app as a display route.

**Comment by bikeoid** [comment]
This route should be available from the API: Query GET /api/v1/Routes/Active , and in theory, the LunchLink route should be returned during its time slot.   All route path(s) returned from this call can be displayed from the data returned in each API call GET /api/v1/Routes/:ID .

**Comment by bikeoid** [comment]
I've entered some fake 24 hour active routes for Tuesday and Wednesday so that GET /api/v1/Routes/Active will return something.
