### ISSUE TITLE
A quick note

### ISSUE THREAD

**Issue by agautsc** [hackgvl/trolley-tracker#23]
Last night close to 500 folks showed up to an event put on by the Greenville news to help bridge the gap between the Greenville of Top Ten Lists (the cool downtown Greenville) and the rest of Greenville. A theme that was so loud and clear in the meeting that it made it to the write-up in the Greenville News http://www.greenvilleonline.com/story/news/local/2015/06/09/crowded-unseen-greenville-forum-begins-larger-community-conversation/28777223/ was transportation. 

"In particular, the theme of transportation arose throughout the night."

This morning, I was at Upstate Transit Coalition meeting and the need for a better and more advanced technology solution for transit came up again. They want to help the Trolley Tracker succeed. 

This project is something that's cool and going to be a nice to have for the trolley, but it could also be something that helps solve a bigger issue in our community. I know we all know this already, but I figured it was worth sharing again as we Voltron this bad boy up next week.

**Comment by jeremywight** [comment]
Awesome! Thank you for that Adam! We have had a lot of people RSVP to the
Hack Night including Ryan Poolos of the CocoaHeads group. Looking to be a
great night to get it over the hump!

**Comment by jeremywight** [comment]
Publicly accessible PivotalTracker Project for the different components https://www.pivotaltracker.com/n/projects/1367484
