### ISSUE TITLE
Slack for CFG

### ISSUE THREAD

**Issue by agautsc** [hackgvl/trolley-tracker#25]
In case y'all are afraid to talk face-to-face https://hackgreenville.slack.com/messages/cfg/ and to get an invite to Hack Greenville in general https://hackgreenville.typeform.com/to/sBMjCF

**Comment by jeremywight** [comment]
I want in! jeremy@jeremywight.com

**Comment by agautsc** [comment]
Head here for an invite https://hackgreenville.typeform.com/to/sBMjCF
