### ISSUE TITLE
Trolley Tour

### ISSUE THREAD

**Issue by agautsc** [hackgvl/trolley-tracker#26]
I went on a "tour" (meaning I sat in the front seat, took some photos, and talked with folks who run the trolleys) for a while today.

You can see the photos here. https://goo.gl/photos/yzLLz2YFt6ad1ggn6 

Three notes and TL;DR
1) They have Galaxy Tab 3's already on the trolley https://goo.gl/photos/28v38Fim3VL37hdt6 The Tab 3's have wireless and, I think, GPS. It gets a little confusing as the trolley literally has two different GPS devices besides the tablet and I'm not sure if the location info is coming from inside the device or from one of these other devices. However, I think there is a good chance we could install the software on the Galaxy Tab 3 without having to buy and install new hardware. 

2) They have a ton of electronics running into the trolley right now. You can see most of their panel of tech, that is stored in a locked dropdown ceiling thing, here https://goo.gl/photos/7sv67ukRgNBorkPf6 They are still waiting on more things to add to this panel and might even have to create a second panel.

3) They are pulling a ton of power to run this trolley. Clicking through the rest of the pictures you can see all kinds of things that go beep and bop and more to come. It's not like a phone would pull that much more power, but if we don't have to add power then we shouldn't.

My TL;DR - I think it's worth getting @ajhodges on a trolley to check out the tablet and see if it's something that can run his beacon. If a separate phone is the only way we can make things work we should investigate a way to mount the phone on the backside of the tablet and use some type of http://www.amazon.com/Dual-Micro-Splitter-Charge-Cable/dp/B004IMEN7C (not that exactly but you get the idea) to power the tablet and phone without having to ask them to run another power line.

**Comment by agautsc** [comment]
FWIW, this wrote about using a Galaxy Tab 3 as the a primary in-car GPS system http://www.zdnet.com/article/using-the-samsung-galaxy-tab-3-as-a-dedicated-car-gps/

**Comment by ajhodges** [comment]
Whoa, looks like they already have cell connectivity. If these things have internet then we can 100% definitely use them. That eliminates our monthly expense and the need for an enclosure as well! This looks VERY promising! I wonder how consistent their internet connection is throughout the route.

Our app will run in the background of the tablet and be completely transparent to the drivers if they are using the tablet for something (dispatching/navigation/whatever?). The only issue I see potentially being an issue is gaining remote access to the tablet for admin tasks like rebooting, etc. We could possibly build some admin functions in to our app.

Good find @agautsc

**Comment by ajhodges** [comment]
@agautsc is there any way you can get the name of the IT guy/gal (that presumably exists) who 'owns' the tablets and controls whatever goes on them, and then drag him/her to our meeting?

**Comment by jeremywight** [comment]
Yeah! Thanks all! See you tomorrow!
