### ISSUE TITLE
Route Updates & Tour of the Trolley

### ISSUE THREAD

**Issue by agautsc** [hackgvl/trolley-tracker#27]
@ajhodges and I visited with GreenLink yesterday. Here are three take aways from meeting.
# Route Update

Starting after the baseball season the trolley route will change to accommodate events at the Bon Secour Center. The route will stay the same unless there is a "special event" at Bon Secour. Then the route will detour to loop around Bon Secour. There will be some known in advance events like hockey games, but all the days and events aren't known. 
## What does this mean?
1. We're going to have to update the routes to include special Bon Secour Route. @bikeoid Is this a you task?
2. The answer "routes change very infrequently if ever" we got early in the process has changed. I don't think we're going to be able to preprogram the dates for special routes into the system and it might be better to make a screen that allows GreenLink the ability to set routes for the week. My idea being there is screen with Sun, Mon, Tues etc and a drop down for Route 1, 2, 3. GreenLink selects the right route for the day on the Friday before and hits submit. Something like that. 
# Tablet software install

GreenLink is going to check to make sure installing another software on the tablet doesn't mess with the warranty / service contract of the company that the tablet was originally purchased for. If it doesn't we're going to install the beacon one of the tablets to test things out. 
# Trolley Tour Round 2

I'm going to setup another tour of the trolley. (Tour is big a word for what this is but you get the idea) Hodges has some questions and wants to look at the Tablet. If anyone else would be interested in coming and could do it probably Mon - Wed in between 1pm and 3pm let me know. I'm going to try to set something up in the next week or so.

**Comment by jeremywight** [comment]
Let me know when it's scheduled for and I will do my best to come.

Jeremy

**Comment by dacohenii** [comment]
@Linktheoriginal and I will also need to make sure the route changes are incorporated into the webapp.

**Comment by Linktheoriginal** [comment]
Right now it's running off of flat 'dummy' data files for route/stop information, but it's written in a way that would make it easy to pull the route and stop information from the API- we'd need to add date/times to the routes to know when to show each one.

Right now, everything is basically a set of lat/lng points.  When a route changes, we'd need to have a resource to generate the route data, or we'd have to figure it out by looking at the trolleys' routes in the collected data (but that data will be messy).

**Comment by bikeoid** [comment]
GTFS would be a good model to use for our datastore - that way if Greenlink were to ever publish that format, we could pull it directly from them.   It would support everything mentioned in the issue list.

If we re-work the datastore, how do people feel about different tools?   I'm too easily discouraged by the command line.   For example, while Microsoft .NET dev tools are boring, we might find it easier to get backup resources. Several people from the GSP .NET developers group were interested in the beginning, but dropped out when it didn't sound like any parts of the project could use .NET.

Otherwise, conceptually, it will also work to keep adding needed elements to our existing datastore (time permitting!).

**Comment by agautsc** [comment]
Email from Kathy at Greenlink 
"I’m talking with the RM folks at 10 am on Monday regarding use of the tablet. He doesn’t think it will be a problem just wants a bit more info. I’ll let you know."
