### ISSUE TITLE
Make sure everything is published with a smart open source license.

### ISSUE THREAD

**Issue by agautsc** [hackgvl/trolley-tracker#33]
https://codeforgvl.imaginethat.io/trolleytracker/i/5181

**Comment by agautsc** [comment]
I think our friend @BigBlueHat usually suggest http://www.apache.org/licenses/LICENSE-2.0

**Comment by agautsc** [comment]
From an email from Benjamin 

"Definitely. The only "gotcha" is according the FSF it's not compatible with GPLv2--though it is compatible with v3. The Apache Software Foundation (ASF) has always held that GPLv2 and Apache 2.0 licenses were never incompatible…but ya know…

Beyond that little quibble it's got the most coverage and safety valves of all the liberal (non-copyleft) licenses. It's also a giant gate key for getting code into the enterprise. :)

Checkout this site for some pretty bullet points that sum stuff up:
http://choosealicense.org"

**Comment by BigBlueHat** [comment]
Yes. Yes, he does. :smiley_cat:

MIT and BSD are also great, but mostly get used for libraries not applications.

The pretty (though completely not legally binding) bullet points on this site may help:
http://choosealicense.com/licenses/apache-2.0/

**Comment by BigBlueHat** [comment]
Or...you can just read my email to @agautsc :wink:
