### ISSUE TITLE
Update on App Install

### ISSUE THREAD

**Issue by agautsc** [hackgvl/trolley-tracker#38]
Hodges, Jeremy and I went down to the trolley today. The app got installed, but the wifi for the trolley wasn't turned on. :angry: 

This is the note I got from Kathy after I told her "Steve is in touch with Verizon to get the router working for the trolley. I will let you know when that happens."

But still, to celebrate the small victory :beer: of getting the thing workingn briefly while on Hodges phone Wi-Fi hotspot you can go to http://linktheorigi.webfactional.com/trolley/ and see the last (and first) location checkin for the trolley.

**Comment by agautsc** [comment]
Update from Greenlink as of 7/17/2015

"RouteMatch has delivered the Trolley hardware and our Maintenance Techs have successfully installed one (the other Trolley should be completed tonight).  That said, we’re still waiting on Verizon to activate the modems.  I will keep checking on this and will let you know when we’re up and running as soon as I hear.
 
Apologies for the delay on this – we’ve had a terrible time getting anything out of Verizon."

**Comment by ajhodges** [comment]
What is the 'trolley hardware'? Is that the counters? At least they are making progress! :+1:
