### ISSUE TITLE
Had a start and end of day checklist trolley drivers completed on the tablet.

### ISSUE THREAD

**Issue by agautsc** [hackgvl/trolley-tracker#65]
https://codeforgvl.imaginethat.io/trolleytracker/i/5321

**Comment by agautsc** [comment]
Maybe a super simple (to the user) app that allows drivers sign-in and it automatically checks wi-fi and is connected and the app is up and running.

**Comment by ajhodges** [comment]
Could also check to make sure the tablet is plugged in.

My hesitation is that the drivers can't seem to handle pressing the power button on the tablet and then *not* unplugging it, I'm not sure how they'll handle having to do even *more* stuff.

Ideally, don't want to have to try to change the drivers' current behavior. But something like this might be the only way to get everything working reliably.

I'm still leaning towards 'tamper-proofing' the USB port, and maybe coloring the power button to make it more obvious where it is (I think we both struggled to find it at first and we're 'power users'). Maybe color it green somehow?

**Comment by agautsc** [comment]
Green stickering the the power button is a good idea. I've got some stickers. I'll put those in my bag to bring to the next meeting.
