### ISSUE TITLE
Adding routes and training

### ISSUE THREAD

**Issue by agautsc** [hackgvl/trolley-tracker#84]
@bikeoid 

Greenlink is going have special routes for Fall For Greenville and the Wellness Center route. Could adding those routes all be done through http://tracker.wallinginfosystems.com/ ?

If so, would you have some time to train Greenlink folks on the system?

**Comment by bikeoid** [comment]
The routes can be selected on the schedule, after the route path has been defined.   I don't have a good route path editor yet.   I can probably guess at the Fall For Greenville route, but not absolutely sure about the Wellness Center route.   So it's a bit early to train the Greenlink folks.   I hope to have a map-based stop editor soon (with photos); the route path editor is more advanced though.

For schedule, it would be useful to have an auxiliary / override schedule, that can be invoked by specifying  "The Greenville Drive/Swamp Rabbits will be in town for 7:00 games from Tuesday through Sunday 9/3 - 9/7" and they would appear on the schedule and automatically be removed.

**Comment by agautsc** [comment]
Grant can provide a shape file for the alt routes and lat and lon for the stop if that would help.

**Comment by agautsc** [comment]
Grant just made a Github account @greenlinktransit Looping him in to this conversation.

**Comment by bikeoid** [comment]
Yes, the shape files for The Well route and Fall For Greenville and lat/lon for any new stops would be helpful

**Comment by greenlinktransit** [comment]
Who should I email the shapefiles to?  The stops for Fall for Greenville are as follows:

County Square Route : 
- County Square: 34,502832, -82241272
- Augusta @ Main: 34.503925, -82.241575

Kroc Route:
- Kroc Lot: 34.505778, -82.243638
- Greenlink Transfer Station:  34.510156, -82.240411

**Comment by bikeoid** [comment]
Please send them to niceman  (@) att.net

**Comment by agautsc** [comment]
We also have a shared, public Google Drive account if you want to upload these files there too https://drive.google.com/drive/u/0/folders/0B1Wxj_5D6dLNfnFEeXo3a3pFVl9VVmxmWWpaNElCaXJrUXhxNi0ycVdOb3Y2SzRrWExFRTA?ths=true

**Comment by bikeoid** [comment]
Are the coordinates in Google convention / EPSG:4326?   When I try to go to those coordinates in Google, I end up in Laurens County - https://www.google.com/maps/place/34%C2%B030'10.2%22N+82%C2%B014'28.6%22W/@34.5028328,-82.2412778,15z/data=!3m1!4b1!4m2!3m1!1s0x0:0x0 

 Also, can you export the shape in either .SHP format or OpenStreetMap format?  I can't find any way to read Arcgis directly.

 Thanks!
