### ISSUE TITLE
2552

### ISSUE THREAD

**Issue by agautsc** [hackgvl/trolley-tracker#87]
We now have 25 Android beta requests and 52 iOS request.

It's getting popular enough we should probably discuss some next steps.

Anyone interested in getting a coffee or a beer this week to have a little strategy pow wow?

Or we could do it all over Github if easier / better.

**Comment by jeremywight** [comment]
Good timing. I was going to ask you the same... You available tomorrow
morning or early afternoon?

**Comment by agautsc** [comment]
How about tomorrow at 8am at Methodical Coffee?

**Comment by jeremywight** [comment]
Sounds good. See you then

**Comment by agautsc** [comment]
Cool. Anyone else who's interested in coming please do.

**Comment by greenlinktransit** [comment]
I'll join

**Comment by greenlinktransit** [comment]
I'll join you guys for a little bit.

**Comment by jeremywight** [comment]
Awesome
