### ISSUE TITLE
Data usage

### ISSUE THREAD

**Issue by agautsc** [hackgvl/trolley-tracker#88]
From @greenlinktransit 

I saw your GitHub conversation about discussing next steps for the Trolley Tracker.  Before your meeting I wanted you to be aware that our Verizon bill for September came back with large overages on the Trolleys.  We asked city IT to take a closer look at it since we were under the impression that the Trolley Tracker application used very little data. 

IT said that the problem is two-fold….. ½ of the overages were directly related to the Trolley Tracker and the other ½ were due to Android updates.  One trolley used 1.05 GB and the other used 818 MB.  Our plan allows 50MB per unit, so you can imagine what that translates to in overage charges.

Anyway, IT is working with Verizon to redo our Wifi plan so I’m not sure that there’s anything that needs to be done.  Our staff and Board are very supportive of the Trolley Tracker but we need to make sure that we keep our bills as low as possible.

**Comment by ajhodges** [comment]
I didn't realize there was a 50mb data limit.. That is pretty low. I think
both trolleys had OS updates to lollipop (on the order of gigabytes) and we
also enabled automatic updates for apps which will likely consume 100-200mb
each month. We need to keep automatic updates enabled so we can push
updates to the trolley without having to go to the facility and bother Rick
(our app updates will only consume ~3mb a month at most). We can try to
mitigate overages by uninstalling unnecessary apps (so they don't pull
updates).

I am pretty confident that the app itself is not contributing very much to
the overages. Though 50mb is a very low (unreasonably so)  limit and I feel
like you should be able to get a better rate from a competitor. Though I'm
sure contracts play a role in that.

**Comment by greenlinktransit** [comment]
It gets a little confusing but I think we should sit tight and see what our new plan allows.

**Comment by jeremywight** [comment]
Could we just set application updates to only occur on WiFi? I assume it
connects to WiFi when it's back at Green Link HQ.

**Comment by ajhodges** [comment]
Actually the Internet is delivered to the tablet via a local wifi Hotspot
on the trolley so unfortunately there is no way to distinguish between
mobile internet and HQ Internet in the play store app :(

**Comment by bikeoid** [comment]
One thing I found is that the server sets cookies in the response.   I can reduce the total bytes per transaction from 1848 to 1027 bytes by dropping cookies, since the cookies are ignored and not needed by webApi clients anyway.    But we may well be back to the higher number of bytes or more when SSL is available.
