### ISSUE TITLE
Note in an email

### ISSUE THREAD

**Issue by agautsc** [hackgvl/trolley-tracker#98]
"Thanks, as a resident in the North Main area, we’ve have been waiting eon’s for this." -Zach 

Got that note in an email.

**Comment by agautsc** [comment]
"Great app, I've been trying to get the city to do this for 5 years." - Chris

**Comment by agautsc** [comment]
" I live on north main street and I've never been able to use the trolley because I never know where it is. I even have a trolley stop in front of my house.  With this app I was able to see where the trolley was (it was very accurate) and rode it!!  Thank you!  I thought it worked well and have no complaints.
 I know there are two trolleys and at times it only showed one.  I was guessing that the other one was on break.  Is there a way to indicate that or let visitors know that there is another one due to come into service shortly?  Thanks again."

-Victoria

**Comment by jeremywight** [comment]
Aww yeah! Giddyup!

**Comment by agautsc** [comment]
"Just used this app for the first time. Very handy and very accurate! Thanks - this is worth keeping!!" -Burgess
