### ISSUE TITLE
Greenville Drive

### ISSUE THREAD

**Issue by agautsc** [hackgvl/trolley-tracker#99]
I met with the Greenville Drive this morning. They are very excited about the app and we brainstormed ideas like having screens in the stadium and at the ticket office showing off the trolley location. They even brought up the idea of showing the trolley tracker on the big screen after the game.

Also, they offered to share the link to YeahThatTrolley.com to the their social networks today. If any one thinks that's a bad idea speak now or the next hour-ish or I'm going to ask them to send it out.

**Comment by ajhodges** [comment]
![screenshot_2015-10-09-12-30-30](https://cloud.githubusercontent.com/assets/856738/10399602/9caba144-6e81-11e5-8d2f-fcec6e5ff0f6.png)
Styling seems a little off on mobile

**Comment by jeremywight** [comment]
Works for me

**Comment by Linktheoriginal** [comment]
Originally styled it to handle less text than that - I'll see what I can do.  Also, noticing that while I added sorting by day, the 6pm Sat is showing up before the 10am Sat.

**Comment by maryhubbard** [comment]
Suggest 24 hour clock for sorting.  6 pm = 1800.

**Comment by Linktheoriginal** [comment]
Downsized everything, tested on my iPhone 5. Do you guys have a preference between bold route names:
![boldroute](https://cloud.githubusercontent.com/assets/574842/10412135/1e88ea46-6f4a-11e5-89a6-6e419a52a9b2.png)

And bold schedule times?
![boldschedule](https://cloud.githubusercontent.com/assets/574842/10412136/27b4e28c-6f4a-11e5-901c-9ae8decf0be9.png)

**Comment by Linktheoriginal** [comment]
I could also just bold the days - trying to think what I would want to see first if I opened it and no routes were running.

**Comment by Linktheoriginal** [comment]
Going with bold schedule routes - if we make the schedule first, I think it would need to group the days differently.

**Comment by ajhodges** [comment]
Sorry for the ambiguity -  John Mark I was referring to the page not
filling my whole screen, which I think is an issue with the marketing site
itself. Having said that, nice improvements! ;)

**Comment by Linktheoriginal** [comment]
Oh, I think we said that was a 'feature' because otherwise you couldn't scroll?  Mostly because the background _is_ the webapp, so trying to scroll with your finger moves the map.
